services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    sylius.google_tag_manager.enhanced_ecommerce.tracking.resolver.product_detail_impression_data_cache:
        decorates: sylius.google_tag_manager.enhanced_ecommerce.tracking.resolver.product_detail_impression_data
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\Resolver\Cache\ProductDetailImpressionCachedDataResolver
        arguments:
            - "@sylius.google_tag_manager.enhanced_ecommerce.tracking.resolver.product_detail_impression_data_cache.inner"
            - "@cache.app"
            - "%sylius_gtm_enhanced_ecommerce.cache_resolver.product_detail_impressions%"
            - "sylius_gtm_enhanced_ecommerce.cache_resolver.product_detail_impressions"
