services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.add_transaction:
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\TagManager\AddTransaction
        arguments:
            - "@google_tag_manager"
            - "@sylius.context.channel"
            - "@sylius.context.currency"

    sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.checkout_step:
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\TagManager\CheckoutStep
        arguments:
            - "@google_tag_manager"

    sylius.google_tag_manager.enhanced_ecommerce.tracking.resolver.product_detail_impression_data:
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\Resolver\ProductDetailImpressionDataResolver
        arguments:
            - "@sylius.calculator.product_variant_price"
            - "@sylius.context.channel"
            - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.object.factory.product_detail_impression"
            - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.object.factory.product_detail"

    sylius.google_tag_manager.enhanced_ecommerce_tracking.resolver.checkout_step:
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\Resolver\CheckoutStepResolver

    sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.currency_code:
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\TagManager\CurrencyCode
        arguments:
            - "@google_tag_manager"
            - "@sylius.context.currency"

    sylius.google_tag_manager.enhanced_ecommerce_tracking.global.listener.sylius.shop.layout.head:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@SyliusGtmEnhancedEcommercePlugin/Global/head.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.head, method: onBlockEvent }

    sylius.google_tag_manager.enhanced_ecommerce_tracking.object.factory.product_detail:
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\Object\Factory\ProductDetailFactory

    sylius.google_tag_manager.enhanced_ecommerce_tracking.object.factory.product_detail_impression:
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\Object\Factory\ProductDetailImpressionFactory

    sylius.google_tag_manager.enhanced_ecommerce_tracking.twig.extension.parameters:
        class: Titi60\SyliusGtmEnhancedEcommercePlugin\Twig\ParameterExtension
        arguments:
            - "%sylius_gtm_enhanced_ecommerce.features.purchases%"
            - "%sylius_gtm_enhanced_ecommerce.features.product_impressions%"
            - "%sylius_gtm_enhanced_ecommerce.features.product_detail_impressions%"
            - "%sylius_gtm_enhanced_ecommerce.features.product_clicks%"
            - "%sylius_gtm_enhanced_ecommerce.features.cart%"
            - "%sylius_gtm_enhanced_ecommerce.features.checkout%"
        tags:
            - { name: "twig.extension" }
